### ISSUE TITLE
How to exclude subdirectory

### ISSUE THREAD

**Issue by b0ris0v** [objarni/pytddmon#26]
In my project directory there is subdirectory with configuration py file that is a cause of except errors. May I setup ptddmon to ignore this subdirectory (it is hidden directory)?

**Comment by objarni** [comment]
There is no such feature at this moment. A quick-fix for now would be to
modify the regex used to find files. You can find it around line 678 in
pytddmon.py. These lines:
if not static_file_set: regex = ("^[^\\.].*.py") # modify this regex! else:
regex = '|'.join(static_file_set) file_finder = FileFinder(cwd, regex)

Or, perhaps even simpler, add an "if" check in this inner loop of the
actual FileFinder class:


for path, _folder, filenames in os.walk(self.root): # add your if _folder
!= 'cfg': statement here for filename in filenames: if self
.re_complete_match(filename): file_paths.add(
os.path.abspath(os.path.join(path, filename)) )

However, first if I were you, I would ask myself why the config py file
throws an exception when imported at all? Do you follow the Python
convention of a "main script" guard, i.e. if __name__ == '__main__': run()?

**Comment by b0ris0v** [comment]
Excluded folder is .ropeproject in main folder
line 201:
if not ( path[-13:] == '/.ropeproject' ):
                        file_paths.add(
                            os.path.abspath(os.path.join(path, filename))
                        )
